#include "src/game/envfx_snow.h"

const GeoLayout ccm_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_a_Non_Solid_Shit_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_a_Non_Solid_Shit_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_FORCE, ccm_dl_a_Non_Solid_Shit_mesh_layer_0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_a_Non_Solid_Shit_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_a_Non_Solid_Shit_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_a_water_sheet_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_b_water_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_Bounceables_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_k_Actual_level_geo_solid__mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ccm_dl_k_Actual_level_geo_solid__mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_koopa_girls_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_Leaves_non_solid__mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_peir_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_z_flames_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 50000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
