extern const GeoLayout target2_geo[];
extern Lights1 target2_f3dlite_material_lights;
extern Lights1 target2_f3dlite_material_001_lights;
extern Vtx target2_target2_mesh_layer_1_vtx_cull[8];
extern Vtx target2_target2_mesh_layer_1_vtx_0[64];
extern Gfx target2_target2_mesh_layer_1_tri_0[];
extern Vtx target2_target2_mesh_layer_1_vtx_1[96];
extern Gfx target2_target2_mesh_layer_1_tri_1[];
extern Gfx mat_target2_f3dlite_material[];
extern Gfx mat_revert_target2_f3dlite_material[];
extern Gfx mat_target2_f3dlite_material_001[];
extern Gfx mat_revert_target2_f3dlite_material_001[];
extern Gfx target2_target2_mesh_layer_1[];
