extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_clouds3_ci4[];
extern u8 castle_grounds_dl_clouds3_pal_rgba16[];
extern u8 castle_grounds_dl__0x1240_ci4[];
extern u8 castle_grounds_dl__0x1240_pal_rgba16[];
extern u8 castle_grounds_dl_Grass_2_ci8[];
extern u8 castle_grounds_dl_Grass_2_pal_rgba16[];
extern u8 castle_grounds_dl__0x820_ia8[];
extern u8 castle_grounds_dl__0x30E0_ci4[];
extern u8 castle_grounds_dl__0x30E0_pal_rgba16[];
extern u8 castle_grounds_dl__0x2CA0_ci4[];
extern u8 castle_grounds_dl__0x2CA0_pal_rgba16[];
extern Vtx castle_grounds_dl_background1_mesh_layer_0_vtx_cull[8];
extern Vtx castle_grounds_dl_background1_mesh_layer_0_vtx_0[103];
extern Vtx castle_grounds_dl_background2_mesh_layer_0_vtx_cull[8];
extern Vtx castle_grounds_dl_background2_mesh_layer_0_vtx_0[81];
extern Vtx castle_grounds_dl_background3_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_background3_mesh_layer_1_vtx_0[160];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[134];
extern Vtx castle_grounds_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_001_mesh_layer_1_vtx_0[122];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_0[24];
extern Vtx castle_grounds_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_003_mesh_layer_1_vtx_0[5];
extern Gfx castle_grounds_dl_background1_mesh_layer_0[];
extern Gfx castle_grounds_dl_background2_mesh_layer_0[];
extern Gfx castle_grounds_dl_background3_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_001_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_003_mesh_layer_1[];
