extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_f3dlite_material_002_lights;
extern u8 castle_grounds_dl_Material12_i8[];
extern u8 castle_grounds_dl_Material20_ci8[];
extern u8 castle_grounds_dl_Material20_pal_rgba16[];
extern u8 castle_grounds_dl_Material2_i8[];
extern u8 castle_grounds_dl_Material28_i8[];
extern u8 castle_grounds_dl_Material114_i8[];
extern Vtx castle_grounds_dl_MainHub_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_MainHub_mesh_layer_1_vtx_0[96];
extern Vtx castle_grounds_dl_MainHub_mesh_layer_1_vtx_1[16];
extern Vtx castle_grounds_dl_MainHub_mesh_layer_1_vtx_2[30];
extern Vtx castle_grounds_dl_MainHub_mesh_layer_1_vtx_3[256];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[4];
extern Vtx castle_grounds_dl_platforms_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_platforms_mesh_layer_1_vtx_0[178];
extern Vtx castle_grounds_dl_platforms_mesh_layer_1_vtx_1[48];
extern Gfx castle_grounds_dl_MainHub_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_platforms_mesh_layer_1[];
