#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"
#include "liane/geo.inc.c"
#include "pipe/geo.inc.c"
#include "d_hammer_mario/geo.inc.c"
#include "hammer_mario/geo.inc.c"
#include "target/geo.inc.c"
#include "cg_barrier/geo.inc.c"
#include "bounce/geo.inc.c"
#include "schoom_blue/geo.inc.c"
#include "schoom_red/geo.inc.c"
#include "pleaves/geo.inc.c"
#include "leaves_p/geo.inc.c"
#include "palmleaf/geo.inc.c"
#include "PotPlant/geo.inc.c"
#include "PotOrnate/geo.inc.c"
#include "PotFlowerOrnate/geo.inc.c"
#include "PotFloral/geo.inc.c"
#include "mask/geo.inc.c"
#include "light_beam/geo.inc.c"
#include "target2/geo.inc.c"