extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_007_lights;
extern u8 wf_dl_nc_grass_n1D_ia8[];
extern u8 wf_dl_Newgrass4_ia4[];
extern u8 wf_dl_FA32626C6E04C88E07CC548F6FEAE571_ci4[];
extern u8 wf_dl_FA32626C6E04C88E07CC548F6FEAE571_pal_rgba16[];
extern u8 wf_dl_RMGP01_2e9dd88c_1_i4[];
extern u8 wf_dl_fancy_water_i4[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[44];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_1[52];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx wf_dl_plane_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_water_mesh_layer_5_vtx_0[16];
extern Gfx wf_dl_water_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_revert_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx mat_revert_wf_dl_f3dlite_material_002[];
extern Gfx mat_wf_dl_f3dlite_material_007[];
extern Gfx mat_revert_wf_dl_f3dlite_material_007[];
extern Gfx mat_wf_dl_f3dlite_material_006[];
extern Gfx mat_revert_wf_dl_f3dlite_material_006[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_plane_mesh_layer_1[];
extern Gfx wf_dl_water_mesh_layer_5[];
